apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-sprint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-sprint
  template:
    metadata:
      labels:
        app: mlops-sprint
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: mlops-sprint
          image: 149614785185.dkr.ecr.us-east-1.amazonaws.com/mlops-sprint:v3
          ports:
            - containerPort: 8000
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-url
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
