apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-sprint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-sprint
  template:
    metadata:
      labels:
        app: mlops-sprint
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: mlops-sprint
          image: 149614785185.dkr.ecr.us-east-1.amazonaws.com/mlops-sprint:5d99defd8b1bcf37958019ee73c9d17c7feecbe8
          ports:
            - containerPort: 8000
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-url
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow:5000"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: secret_access_key
            - name: AWS_DEFAULT_REGION
              value: us-east-1
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
